### PR TITLE
feat: Maetveis css card banners

### PR DESCRIPTION
**Pull request by samjwu**
Duplicates https://github.com/ROCm/rocm-docs-core/pull/663 after resolving merge conflicts

### CODE REVIEW

**Comment by samjwu** [comment]
@ROCm/rocm-documentation

**Comment by yhuiYH** [comment]
Neat, can we change the source image to this: 
banner-stretched

**Comment by samjwu** [comment]
> Neat, can we change the source image to this: banner-stretched

I misread this as an approval. Feel free to make a new PR with this change

**Comment by yhuiYH** [comment]
> > Neat, can we change the source image to this: banner-stretched
> 
> I misread this as an approval. Feel free to make a new PR with this change

No worries.  I did just that, put up new PR for it: https://github.com/ROCm/rocm-docs-core/pull/915

**Pull request merged**
