### PR TITLE
Css card banners

### PR DESCRIPTION
**Pull request by Maetveis**
Add css classes for card banners

To use them set the option class-body to `rocm-card-banner`.
12 hues are available, add the additional class `rocm-hue-<hue>`.

For example:
```markdown
:::{grid-item-card} Title
:class-body: rocm-card-banner rocm-hue-6
:::
```
Would create a card with a banner of hue 6.

Use these banners on the index page of the documentation, to showcase and
test them.

This will be used to resolve https://github.com/ROCm/ROCm/issues/2907

### CODE REVIEW

**Review by randyh62 — APPROVED** [review]
Looks good.

**Comment by LisaDelaney** [comment]
some changes I'd like:
- can we lower the card text so there more space after the image? 
- I would really like to change the font to something a little more clear/easy on the eyes
- the images are too zoomed in/distorted (related: I want the white text over a mostly black part of the image...so the white text isn't on top of colour): I strongly prefer the images as they are on the [ROCm homepage](https://rocm.docs.amd.com/en/latest/)

**Comment by LisaDelaney** [comment]
> some changes I'd like:
> 
> * can we lower the card text so there more space after the image?
> * I would really like to change the font to something a little more clear/easy on the eyes
> * the images are too zoomed in/distorted (related: I want the white text over a mostly black part of the image...so the white text isn't on top of colour): I strongly prefer the images as they are on the [ROCm homepage](https://rocm.docs.amd.com/en/latest/)

@Maetveis have you been able to look into any of the above? ^

**Comment by saadrahim** [comment]
@MathiasMagnus @parbenc can you look into @LisaDelaney 's requests?

**Pull request merged**
