### PR TITLE
feat(projects.yaml): Add tensile to intersphinx mapping

### PR DESCRIPTION
**Pull request by peterjunpark**
>Documentation for Tensile is now available. Tensile is a library that creates benchmark-driven backend implementations for GEMMs, serving primarily as a backend component of rocBLAS. See the [Tensile documentation](https://rocm.docs.amd.com/projects/Tensile/en/docs-6.3.0/src/index.html).

### CODE REVIEW

**Comment by peterjunpark** [comment]
We don't need Omniperf as it is now covered by rocprofiler-compute. The same is not true for Omnitrace and rocprofiler-systems because the "renamed" rocprofiler-systems will break compatibility with older versions of ROCm in its next breaking release. The Omnitrace documentation site and GitHub repository will remain to support diverse compatibility needs.

**Comment by saadrahim** [comment]
> We don't need Omniperf as it is now covered by rocprofiler-compute. The same is not true for Omnitrace and rocprofiler-systems because the "renamed" rocprofiler-systems will break compatibility with older versions of ROCm in its next breaking release. The Omnitrace documentation site and GitHub repository will remain to support diverse compatibility needs.

I recommend not removing older functionality. Future compliance may require an update of rocm-docs-core for older documentation for things such as corporate template updates or cookie policies. There is no cost to keep this line while removal may limit future options.

**Comment by peterjunpark** [comment]
> > We don't need Omniperf as it is now covered by rocprofiler-compute. The same is not true for Omnitrace and rocprofiler-systems because the "renamed" rocprofiler-systems will break compatibility with older versions of ROCm in its next breaking release. The Omnitrace documentation site and GitHub repository will remain to support diverse compatibility needs.
> 
> I recommend not removing older functionality. Future compliance may require an update of rocm-docs-core for older documentation for things such as corporate template updates or cookie policies. There is no cost to keep this line while removal may limit future options.

Ok, makes sense. Dropped the 'remove omniperf from projects.yaml' commit @saadrahim.

The thing that annoys me is that this warning will keep appearing.
image

IDK if we can suppress this warning somehow?

**Comment by saadrahim** [comment]
why is omniperf latest doc disabled? it should still point to an old version,

**Review by alexxu-amd — APPROVED** [review]

**Review by samjwu — APPROVED** [review]

**Pull request merged**
